export enum MODALS {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  RECOVER_PASSWORD = 'RECOVER_PASSWORD',
  GRAND_CHART = 'GRAND_CHART',
  PREVIEW_NOTES = 'PREVIEW_NOTES',
  PREVIEW_CHART = 'PREVIEW_CHART'
};
