export enum MODALS {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  RECOVER_PASSWORD = 'RECOVER_PASSWORD',
  GRAND_CHART = 'GRAND_CHART',
  PREVIEW_NOTES = 'PREVIEW_NOTES',
  PREVIEW_CHART = 'PREVIEW_CHART',
  CIRCLE_OF_FIFTHS = 'CIRCLE_OF_FIFTHS',
  FRETBOARD_A_B_C = 'FRETBOARD_A_B_C',
  FRETBOARD_DO = 'FRETBOARD_DO',
}

export enum MODALS_GRAND_CHART {
  SCHOOL_GUITAR = '1-1',
  SCHOOL_KEYBOARD = '1-2',
  SCHOOL_SAXOPHONE = '1-4',
  COLLEGE_GUITAR = '2-3',
  COLLEGE_KEYBOARD = '2-5',
  COLLEGE_SAXOPHONE = '2-6',
  UNIVERSITY_GUITAR = '3-7',
  UNIVERSITY_KEYBOARD = '3-8',
  UNIVERSITY_SAXOPHONE = '3-9',
}
